apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-dep71
  labels:
    app: webapp
    version: v7.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
        version: v7.1
    spec:
      containers:
      - name: webapp
        image: myregistry.com:5000/webapp:7.1
        ports:
        - containerPort: 5000
