apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-dep61
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: myregistry.com:5000/webapp:6.1
        ports:
        - containerPort: 5000
